### PR TITLE
Enforce consistent multiline comma

### PR DESCRIPTION
**Pull request by jrmay**

### CODE REVIEW

**Review by toddnestor — APPROVED** [review]
Where do we handle it for javascript/typescript?

**Comment by jrmay** [comment]
@toddnestor in the [Olympus branch here](https://github.com/RaiseMe/raise-ror-webapp/compare/jordan/trailing-commas#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090fR46).

Once this is merged I'll bump the gem version reference and apply the rubocop fixes as well.

**Comment by toddnestor** [comment]
@jrmay woohoo! thanks for handling! This is probably a record for discussion -> implementation for us!

**Comment by jrmay** [comment]
We can also _not_ include the changes themselves in the PR if that's preferred and do it as we update new files. 

I'm hoping GitHub will soon support the ability to ignore specific revisions in blame, [as requested here](https://github.community/t/support-ignore-revs-file-in-githubs-blame-view/3256), but seems doubtful.

**Comment by jrmay** [comment]
@toddnestor Looking at what you've done this afternoon, I think this also might be a record for the relative importance of things Todd is working on to what Jordan is working on.

**Pull request merged**
